---
- hosts: redhat
  become: true
  tasks:
   - name: create a new directory
     file:
       path: /var/lib/jenkins/workspace/simpleansiplay/play-lab
       state: directory
   - name: create a new file
     file:
       path: /var/lib/jenkins/workspace/simpleansiplay/play-lab/play.txt
       state: touch
   - name: create text in the file
     blockinfile:
       path: /var/lib/jenkins/workspace/simpleansiplay/play-lab/play.txt
       block: |
         These lines are added by blockinfile module
         Check out the marker lines
         LogLevel warn
         These lines are added by blockinfile module
         Check out the marker lines
         backup: yes
   - name: modify the line and registerthe system variable for recend step result
     lineinfile:
       path: /var/lib/jenkins/workspace/simpleansiplay/play-lab/play.txt
       regexp: "LogLevel warn"
       line: "LogLevel MUDDALAPRAM ANILKUMAR"
       state: present
       backup: yes
     register: result
   - name: copy thefile playbackup1aaaaa
     copy:
       src: /var/lib/jenkins/workspace/simpleansiplay/play-lab/play.txt
       dest: /var/lib/jenkins/workspace/simpleansiplay/play-lab/playcopy.txt
   - name: if any problem debug display theresult
     debug:
       var: result
       verbosity: 4 
   - name: usage of when
     debug: 
       var: result
     when: result != " "
